/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import pkg490os_project1.Controller;


/**
 *
 * @author Joshua
 */
public class CustomerList extends javax.swing.JFrame {

    /**
     * Creates new form CustomerList
     */
    private Controller controller;
    private LinkedList<String> customer_data;
    
    public CustomerList(Controller controller) {
        this.controller = controller;
        EventHandler handler=new EventHandler();
        this.customer_data = new LinkedList<String>();
        customer_data.add("ID");
        customer_data.add("Name");
        customer_data.add("Telephone");
        customer_data.add("Address");
        initComponents();
        updateTable();
        searchBtn.addActionListener(handler);
        rentBtn.addActionListener(handler);
        rentedBtn.addActionListener(handler);
        addCustomerBtn.addActionListener(handler);
    }

    private void updateTable() {
        this.customersTbl.setModel(new DefaultTableModel(controller.findCustomer(""),customer_data.toArray()));
    }

    class EventHandler implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == searchBtn){
                try{
                Object[][] customers=controller.findCustomer(search_field.getText());
                customersTbl.setModel(new DefaultTableModel(customers,customer_data.toArray()));
                
                }
                catch(Exception exp)
                {
                    System.out.println("error"+exp.getMessage());
                    
                }
            } else if (e.getSource() == rentBtn) {
                Object o;
                int row = customersTbl.getSelectedRow();
                if (row >= 0) {
                    o = customersTbl.getValueAt(row, 0);
                    System.out.println(o);
                    java.awt.EventQueue.invokeLater(() -> {
                        CustomerActions actionForm = new CustomerActions(controller, (String) o);
                        actionForm.setVisible(true);
                    });
                }
            }else if (e.getSource() == rentedBtn) {
                    Object o1;
                    int row1 = customersTbl.getSelectedRow();
                    if (row1 >= 0) {
                        o1 = customersTbl.getValueAt(row1, 0);
                        java.awt.EventQueue.invokeLater(() -> {
                            CustomerActions actionForm = new CustomerActions(controller, (String) o1);
                            actionForm.setVisible(true);
                        });
                    }
            }else if (e.getSource() == addCustomerBtn) {
                java.awt.EventQueue.invokeLater(() -> {
                    AddCustomer actionForm = new AddCustomer();
                    actionForm.setVisible(true);
                });
                throw new UnsupportedOperationException("Not supported yet.");
            } //To change body of generated methods, choose Tools | Templates.
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rentBtn = new javax.swing.JButton();
        rentedBtn = new javax.swing.JButton();
        search_field = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        customersTbl = new javax.swing.JTable();
        addCustomerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rentBtn.setText("Rent Car");

        rentedBtn.setText("Rented Cars");

        searchBtn.setText("Search");

        customersTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(customersTbl);

        addCustomerBtn.setText("Add Customer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rentBtn)
                        .addGap(18, 18, 18)
                        .addComponent(rentedBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCustomerBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentBtn)
                    .addComponent(rentedBtn)
                    .addComponent(addCustomerBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerBtn;
    private javax.swing.JTable customersTbl;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton rentBtn;
    private javax.swing.JButton rentedBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField search_field;
    // End of variables declaration//GEN-END:variables
}
