/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg490os_project1;

import java.util.Collection;
import java.util.Iterator;

/**
 *
 * @author Joshua
 */
public class CustomerList extends javax.swing.JFrame {

    /**
     * Creates new form CustomerList
     */
    private Container customers;
    private Container rentals;
    
    public CustomerList(Container customers, Container rentals) {
        this.customers=customers;
        this.rentals=rentals;
        initComponents();
        updateTable();
    }
    private String[][] getCustomersAsArray(Collection<Customer> customers) {
        String[][] result = new String[customers.size()][3];
        int i = 0;
        for (Iterator iterator = customers.iterator(); iterator.hasNext();) {
            Customer cust = (Customer) iterator.next();
            result[i] = cust.to_array();
            System.out.print(result[i]);
            i++;
        }
        return result;
    }

    private void updateTable() {
        String[][] rowData = getCustomersAsArray(customers.contains(search_field.getText().trim()));
        String[] columns = {"Name", "Phone Number", "Address"};
        customersTbl.setModel(new javax.swing.table.DefaultTableModel(rowData, columns));
    }

    private Customer getSelCustomer(Collection<Customer> customers) {
        int i = 0;
        for (Iterator iterator = customers.iterator(); iterator.hasNext();) {
            Customer cust = (Customer) iterator.next();
            if (customersTbl.getSelectedRow() == i) {
                return cust;
            }
            i++;
        }
        return new Customer("123", "Wong", "914-2602", "1326 Baker Drive");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rentBtn = new javax.swing.JButton();
        rentedBtn = new javax.swing.JButton();
        search_field = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        customersTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rentBtn.setText("Rent Car");
        rentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentBtnActionPerformed(evt);
            }
        });

        rentedBtn.setText("Rented Cars");
        rentedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentedBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        customersTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(customersTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rentBtn)
                        .addGap(18, 18, 18)
                        .addComponent(rentedBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentBtn)
                    .addComponent(rentedBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            CustomerActions actionForm = new CustomerActions(getSelCustomer(customers.contains(search_field.getText().trim())), rentals);
            actionForm.setVisible(true);
        });
    }//GEN-LAST:event_rentBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        updateTable();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void rentedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentedBtnActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            CustomerActions actionForm = new CustomerActions(getSelCustomer(customers.contains(search_field.getText().trim())), rentals);
            actionForm.setVisible(true);
        });
    }//GEN-LAST:event_rentedBtnActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable customersTbl;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton rentBtn;
    private javax.swing.JButton rentedBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField search_field;
    // End of variables declaration//GEN-END:variables
}
